[book]
authors = ["lencx"]
language = "zh_CN"
title = "MDH • 前端情报"
multilingual = false
src = "src"

[rust]
edition = "2018"

# https://github.com/lzanini/mdbook-katex
# [preprocessor.katex]

# https://github.com/badboy/mdbook-mermaid
# [preprocessor.mermaid]
# command = "mdbook-mermaid"

[output.html]
theme = "theme"
default-theme = "ayu"
no-section-label = true
git-repository-url = "https://github.com/fe-cool/news"
additional-css = ["theme/news.css"]
# additional-js = [
#   # "plugins/mermaid.min.js",
#   # "plugins/mermaid.init.js",
# ]

[output.html.playground]
editable = true
copy-js = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 3
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[output.html.fold]
enable = true
level = 2